### ISSUE TITLE
Enhancements to get this functionality “offline”

### ISSUE THREAD

**Issue by mzpqnxow** [gamozolabs/proc_mem_ida_loader#1]
First, thanks for writing this

I wanted to do something sort of similar to this a while ago, but didn’t follow through and have been looking for prior work- finally finding this - very happy to find it

However, I read a bit and realized it doesn’t _quite_ suit my needs- still a ton of value, but I can’t use it without a lot of modifications 

My use-case:

1. IDA running on MacOS
2. ELF running on remote linux system to be analyzed (it happens to be a different CPU architecture and is also non-trivial to adapt to run in qemu- though I’m not sure that matters anyway)

If I understand correctly (I read the docs, not the code) you read proc mem to acquire the memory directly. This definitely simplifies things a little, I see why you chose that approach. Unfortunately, though, it’s problematic for my use-case

I had a couple of ideas on how I might be able to adapt this rather than doing what I want from scratch (again, not yet having read the code, sorry for any misunderstanding)

1. I could put shims into your plugin, enough so that accessing /proc/pid/mem (effectively) “works” on windows, without modifying much of the more intelligent logic. Something like a wrapper in Python for open() as well as seek()+read() or pread() - whatever is needed to emulate reading proc mem. Those wrappers would effectively forwarding the operations to the remote system, or would operate on a local core file. Hacky, but it should work, theoretically
2. Alternately, a more proper solution, grab a core of the Linux process using gcore, copy to the system with IDA, load the core, then steal and adapt the parts of your code that lift the symbol info into IDA
3. Something using gdbserver. I work a lot with gdbserver but have never used IDA as a gdbserver client, so I’m not too knowledgeable about how it works. Though I imagine I would ultimately be reinventing gdbserver to some extent if I took approach 1

Do you have any better ideas, and/or are you interested in doing the work? Any glaring flaws in these ideas? Maybe I’m missing a simple and obvious way around this?

I don’t have the time at the moment to work on this myself, but it’s on my list..

I’m not expecting you to have the time or interest, but thought I would ask anyway 😃 

Thanks again, neat plugin. I really appreciate seeing custom loaders and CPU architecture plugins because they aren’t documented very well, and are difficult to grasp without actually seeing or writing one (the open source nios2 CPU loader is a nice example of a non-trivial CPU plugin, if you’re interested in checking it out)

**Comment by mzpqnxow** [comment]
Nevermind, I’m an idiot and completely missed that dwarf symbols were required- for some reason I thought you were constructing a minimalist dwarf file to get the symbols into IDA. Don’t mind me 😃

**Comment by gamozolabs** [comment]
Dwarf symbols shouldn't be _required_, unless y ou want symbols. All this really does is just list `/proc/pid/maps` to get the virtual memory mappings, then uses `/proc/pid/mem` to read the contents of memory, then it creates those sections and permissions in IDA. The symbols are applied if there are symbols.

Making this work remote is possible, in theory it would work over something like smb/nfs I think (never tried `/proc` over network).

Your usecase (over the network/on a different machine) is kinda too niche for me to want to add, since I want to keep this plugin as simple as possible, such that it's easy to modify and understand. With a core dump you can just load it directly in IDA, you could maybe try to steal just the symbol applying logic from my code, but it'd have to be able to "find" the original binaries (eg. copy them off the machine or something).

**Comment by mzpqnxow** [comment]
> Dwarf symbols shouldn't be _required_, unless y ou want symbols. All this really does is just list `/proc/pid/maps` to get the virtual memory mappings, then uses `/proc/pid/mem` to read the contents of memory, then it creates those sections and permissions in IDA. The symbols are applied if there are symbols.

Interesting. I was basing my assumption here on how the core file loader works; as far as I could tell, the loader+analysis doesn't do anything to try to determine which segments are imports, or do anything with import/relocation information or symbol table sections. Maybe I'm thinking about it wrong (probably) or my core was truncated or there was some other pilot error (also, probably)

> Making this work remote is possible, in theory it would work over something like smb/nfs I think (never tried `/proc` over network).

Yeah, would be interesting to try NFS. I have my doubts as I seem to recall that some very basic files (e.g. /proc/version, /proc/cmdline, etc) don't even function fully with stat() - if I remember correctly, the size is reported at 0. Though that doesn't necessarily mean anything here, I don't think you really need stat() for anything here anyway since you get the size information via the range info from maps

My other pessimism might be more relevant, and comes from knowing that NFS doesn't have a seek procedure; instead it uses offset arguments to the read and write procedures. That may be the killer, if you can't seek+read, you're dead in the water right?

Could still be a SYS_seek underneath there though, who knows. So I should stop speculating and either try it or wait until someone else does

It's interesting to me for other cases- because if it *did* work, it could be a crafty way to _immediately_ execute arbitrary code via NFS, assuming appropriate permissions - getting important addresses from /proc/self/stat and then writing into process memory via /proc/self/mem to get pc control. That idea is inspired (stolen, really) from the "bug" (accidental feature?) of OpenSSH sftp-server implementation that was fixed years ago, which did something like this, I think. Though sftp-only shell access was/is a much more common thing to run into than NFS with rw /proc hah

Anyway, sorry, way off topic here!

> Your usecase (over the network/on a different machine) is kinda too niche for me to want to add, since I want to keep this plugin as simple as possible, such that it's easy to modify and understand. With a core dump you can just load it directly in IDA, you could maybe try to steal just the symbol applying logic from my code, but it'd have to be able to "find" the original binaries (eg. copy them off the machine or something).

Yeah, that's a totally sane stance. Frankly, I'm somewhat relieved you didn't mock me for asking 😂 

Appreciate the response and thanks again for the project!
